

const lng = {
  ru: {
    enterExam: "Вступительные тесты",
    year: "год",
    start: "Начать",
    back: "Назад",
    formTitle: "Введите данные",
    firstName: "Имя",
    lastName: "Фамилия",
    surName: "Отчество",
    dateOfBirth: "Дата рождения",
    phone: "Номер телефона",
    comeFrom: "Область / Город",
    chooseRegion: "Выберите область",
    tashkent: "город Ташкент",
    lodging: "Место жительство",
    totalTime: "Таймер",
    tashkentRegion: "Ташкентская область",
    namangan: "Наманганская область",
    fergana: "Ферганская область",
    andijan: "Андижанская область",
    syrdaryo: "Сырдарьинская область",
    jizzakh: "Джизакская область",
    samarqand: "Самаркандская область",
    navoiy: "Навоийская область",
    bukhara: "Бухарская область",
    qashqadaryo: "Кашкадарьинская область",
    surxondaryo: "Сурхандарьинская область",
    khorezm: "Хорезмская область",
    karakalpakstan: "Республика Каракалпакстан",
    other: "Другие",
    quizRules: "После запуска таймер не может быть остановлен. Ваши ответы будут отправлены автоматически, когда истечет время. Пожалуйста, подготовьтесь перед началом.",
    testEnd: "Тест завершен",
    testTimeEnd: "Время закончилось, все ваши ответы сохранены!",
    seeAnswers: "Посмотреть ответы"
  },
  uz: {
    enterExam: "Bilimingizni sinab ko'ring",
    year: "yil",
    formTitle: "Ma'lumotlaringizni kiriting",
    start: "Boshlash",
    back: "Ortga",
    firstName: "Ism",
    lastName: "Familiya",
    surName: "Sharif",
    dateOfBirth: "Tug'ilgan kun",
    phone: "Telefon raqamingiz",
    comeFrom: "Viloyat / Shahar",
    chooseRegion: "Viloyatingizni tanlang",
    tashkent: "To'shkent shahri",
    lodging: "Turar joy",
    totalTime: "Umumiy vaqt",
    tashkentRegion: "To'shkent viloyati",
    namangan: "Namangan",
    fergana: "Farg'ona",
    andijan: "Andijon",
    syrdaryo: "Sirdaryo",
    jizzakh: "Djizzax",
    samarqand: "Samarqand",
    navoiy: "Navoiy",
    bukhara: "Buxoro",
    qashqadaryo: "Qashqadaryo",
    surxondaryo: "Surxondaryo",
    khorezm: "Xorazm",
    karakalpakstan: "Qoraqalpog'iston",
    other: "Boshqa",
    quizRules: "Bir marta boshlaganingizdan so'ng, taymerni to'xtatib bo'lmaydi. Vaqt tugashi bilan javoblaringiz avtomatik ravishda yuboriladi. Iltimos, boshlashdan oldin tayyorlaning.",
    testEnd: "Test tugadi!",
    testTimeEnd: "Test vaqti tugadi.<br/>Barcha javoblaringiz saqlandi!",
    seeAnswers: "Javobni ko'rish"
  }
};

export default lng;